# Checkov configuration
framework:
  - terraform

skip-check:
  # Add check IDs to skip here if needed
  # - CKV_AWS_1

# Compact output format
compact: true

# Quiet mode (minimal output)
quiet: false

# Download external modules
download-external-modules: true
